- name: Install ZSH
  yum:
    name: zsh
    state: latest
  become: yes

- name: Get ZSH install location
  shell: command -v zsh
  register: zsh_location

- name: Add ZSH to /etc/shells
  lineinfile:
    dest: /etc/shells
    line: "{{ item }}"
    state: present
  with_items: "{{ zsh_location.stdout_lines }}"
  become: yes

- name: Make ZSH default shell for current user
  user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ item }}"
  with_items: "{{ zsh_location.stdout_lines }}"
  become: yes