- name: Download Packer
  get_url:
    url: https://releases.hashicorp.com/packer/1.2.2/packer_1.2.2_linux_amd64.zip
    dest: ~/

- name: Unpack Packer
  unarchive:
    src: ~/packer_1.2.2_linux_amd64.zip
    dest: ~/
    remote_src: yes