- name: Download Rustup to temp file
  get_url: 
    url: https://sh.rustup.rs
    dest: ~/rustup.sh

- name: Run Rustup installer
  command: sh ~/rustup.sh -y

- name: Source bash_profile
  command: source ~/.bash_profile

- name: Add toolchains
  command: rustup install {{ item }}
  with_items:
    - stable
    - nightly

- name: Make stable toolchain default
  command: rustup default stable

- name: Add rust stable components
  command: rustup component add {{ item }} --toolchain stable
  with_items:
    - rls-preview
    - rust-analysis
    - rust-src

- name: Install Racer
  command: cargo install racer
  args:
    creates: ~/.cargo/bin/racer