- name: Update packages
  yum:
    name: '*'
    state: latest
    update_cache: yes
  become: yes

- name: Add EPEL
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/7/$basearch/
  become: yes

- name: Install EPEL GPG Key
  rpm_key:
    state: present
    key: https://archive.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7