- name: Update packages
  yum:
    name: '*'
    state: latest
    update_cache: yes
  become: yes

- name: Enable EPEL
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.nparch.rpm
    state: latest
  become: yes