- name: Update packages
  yum:
    name: '*'
    state: latest
  become: yes

- name: Add EPEL
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  become: yes